name: Publish Python Package to PyPi on Release
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish
